// Embedded dataset for VMG Ventas dashboard prototype
window.DATA = {
  meta: {
    facturas: 1021,
    vendedores: 6,
    clientes: 126,
    productos: 877,
    provinciasOps: 17,
    totalPeriodo: 5302, // millones ARS
    periodo: 'Enero–Abril 2026',
  },
  ventasMensuales: [
    { mes: 'ene', total: 1580, unidades: 95000, completo: true },
    { mes: 'feb', total: 1420, unidades: 88500, completo: true },
    { mes: 'mar', total: 1392, unidades: 92800, completo: true },
    { mes: 'abr', total: 912, unidades: 56207, completo: false },
  ],
  vendedores: [
    { nombre: 'Guillermo Cabral', facturas: 801, clientes: 83, total: 4026, porc: 76 },
    { nombre: 'Diego Santoni', facturas: 140, clientes: 19, total: 942, porc: 18 },
    { nombre: 'Ruben Hosenen', facturas: 30, clientes: 7, total: 236, porc: 4.5 },
    { nombre: 'Rgalvalisi', facturas: 14, clientes: 6, total: 49, porc: 0.9 },
    { nombre: "Rodolfo D'andrea", facturas: 35, clientes: 12, total: 47, porc: 0.9 },
    { nombre: 'Victor Fanari', facturas: 1, clientes: 1, total: 0.28, porc: 0.0 },
  ],
  topProductosAbril: [
    { codigo: 'BA1358', monto: 46.0, unidades: 4200 },
    { codigo: 'BA434',  monto: 30.6, unidades: 3850 },
    { codigo: 'RF003',  monto: 28.4, unidades: 21500 },
    { codigo: 'BA504',  monto: 25.4, unidades: 2100 },
    { codigo: 'BA478',  monto: 23.6, unidades: 1980 },
    { codigo: 'BA1076', monto: 19.4, unidades: 2400 },
    { codigo: 'BA691',  monto: 14.3, unidades: 1620 },
    { codigo: 'BA442',  monto: 14.0, unidades: 1480 },
    { codigo: 'BA1473', monto: 13.6, unidades: 1320 },
    { codigo: 'BA429',  monto: 13.5, unidades: 1400 },
  ],
  provincias: [
    { nombre: 'Buenos Aires',    total: 3384, porc: 64,  facturas: 418, clientes: 43 },
    { nombre: 'Santa Fe',        total: 833,  porc: 16,  facturas: 275, clientes: 32 },
    { nombre: 'Córdoba',         total: 477,  porc: 9,   facturas: 124, clientes: 15 },
    { nombre: 'Tucumán',         total: 131,  porc: 2.5, facturas: 23,  clientes: 4 },
    { nombre: 'Chaco',           total: 97,   porc: 1.8, facturas: 18,  clientes: 3 },
    { nombre: 'Mendoza',         total: 86,   porc: 1.6, facturas: 24,  clientes: 4 },
    { nombre: 'Entre Ríos',      total: 62,   porc: 1.2, facturas: 21,  clientes: 3 },
    { nombre: 'Ciudad de Buenos Aires', total: 52, porc: 1.0, facturas: 20, clientes: 4 },
    { nombre: 'San Juan',        total: 43,   porc: 0.8, facturas: 13,  clientes: 1 },
    { nombre: 'La Pampa',        total: 30,   porc: 0.6, facturas: 17,  clientes: 2 },
    { nombre: 'Río Negro',       total: 22,   porc: 0.4, facturas: 9,   clientes: 2 },
    { nombre: 'Salta',           total: 18,   porc: 0.3, facturas: 7,   clientes: 2 },
    { nombre: 'San Luis',        total: 15,   porc: 0.3, facturas: 6,   clientes: 1 },
    { nombre: 'Misiones',        total: 12,   porc: 0.2, facturas: 5,   clientes: 1 },
    { nombre: 'Corrientes',      total: 10,   porc: 0.2, facturas: 4,   clientes: 1 },
    { nombre: 'Jujuy',           total: 6,    porc: 0.1, facturas: 3,   clientes: 1 },
    { nombre: 'Neuquén',         total: 4,    porc: 0.1, facturas: 2,   clientes: 1 },
  ],
  // Detalle a nivel cliente × producto. Montos en M ARS, unidades absolutas.
  clientesDetalle: [
    { cliente: 'BBA Autopartes S.A.',          articulo: 'BA1358', provincia: 'Bs As',    ventaActual: 28.4, varDinero: -9.2,  unidadesActual: 2600, varUnidades: -540 },
    { cliente: 'BBA Autopartes S.A.',          articulo: 'BA434',  provincia: 'Bs As',    ventaActual: 21.0, varDinero: -7.1,  unidadesActual: 2640, varUnidades: -380 },
    { cliente: 'Sispare S.A.',                 articulo: 'BA504',  provincia: 'Bs As',    ventaActual: 19.8, varDinero: -6.4,  unidadesActual: 1640, varUnidades: -260 },
    { cliente: 'Sispare S.A.',                 articulo: 'BA478',  provincia: 'Bs As',    ventaActual: 18.2, varDinero: -5.0,  unidadesActual: 1525, varUnidades: -180 },
    { cliente: 'Ventor S.A.C.E.I',             articulo: 'BA1358', provincia: 'Bs As',    ventaActual: 17.6, varDinero: 1.4,   unidadesActual: 1610, varUnidades: 90 },
    { cliente: 'Ventor S.A.C.E.I',             articulo: 'RF003',  provincia: 'Bs As',    ventaActual: 14.2, varDinero: 0.8,   unidadesActual: 10750, varUnidades: 520 },
    { cliente: 'DER S.A.',                     articulo: 'BA1076', provincia: 'Bs As',    ventaActual: 16.7, varDinero: 5.4,   unidadesActual: 2065, varUnidades: 610 },
    { cliente: 'DER S.A.',                     articulo: 'BA691',  provincia: 'Bs As',    ventaActual: 14.3, varDinero: 4.9,   unidadesActual: 1620, varUnidades: 510 },
    { cliente: 'Rural Santa Fe SAICA',         articulo: 'BA1473', provincia: 'Santa Fe', ventaActual: 13.6, varDinero: -1.0,  unidadesActual: 1320, varUnidades: -90 },
    { cliente: 'Rural Santa Fe SAICA',         articulo: 'BA442',  provincia: 'Santa Fe', ventaActual: 12.1, varDinero: -0.6,  unidadesActual: 1280, varUnidades: -50 },
    { cliente: 'Multioriginal Parts S.A.',     articulo: 'BA429',  provincia: 'Bs As',    ventaActual: 13.5, varDinero: 2.6,   unidadesActual: 1400, varUnidades: 230 },
    { cliente: 'Multioriginal Parts S.A.',     articulo: 'BA478',  provincia: 'Bs As',    ventaActual: 12.4, varDinero: 2.4,   unidadesActual: 1040, varUnidades: 200 },
    { cliente: 'Montanini Pablo y Tilbe Juan P.', articulo: 'BA434', provincia: 'Bs As',  ventaActual: 11.8, varDinero: -2.4,  unidadesActual: 1480, varUnidades: -260 },
    { cliente: 'Montanini Pablo y Tilbe Juan P.', articulo: 'BA504', provincia: 'Bs As',  ventaActual: 10.9, varDinero: -2.2,  unidadesActual: 905,  varUnidades: -160 },
    { cliente: 'Autocor SRL',                  articulo: 'BA1358', provincia: 'Córdoba',  ventaActual: 14.0, varDinero: 5.1,   unidadesActual: 1280, varUnidades: 470 },
    { cliente: 'Autocor SRL',                  articulo: 'BA1076', provincia: 'Córdoba',  ventaActual: 9.4,  varDinero: 3.4,   unidadesActual: 1160, varUnidades: 420 },
    { cliente: 'Lubrax Centro S.R.L.',         articulo: 'RF003',  provincia: 'Córdoba',  ventaActual: 8.6,  varDinero: -0.6,  unidadesActual: 6500, varUnidades: -300 },
    { cliente: 'Lubrax Centro S.R.L.',         articulo: 'BA429',  provincia: 'Córdoba',  ventaActual: 7.2,  varDinero: -0.5,  unidadesActual: 750,  varUnidades: -40 },
    { cliente: 'Repuestera del Norte S.A.',    articulo: 'BA1358', provincia: 'Tucumán',  ventaActual: 9.4,  varDinero: 3.6,   unidadesActual: 860,  varUnidades: 320 },
    { cliente: 'Repuestera del Norte S.A.',    articulo: 'BA504',  provincia: 'Tucumán',  ventaActual: 6.8,  varDinero: 2.6,   unidadesActual: 560,  varUnidades: 220 },
    { cliente: 'Casa Hidráulica S.R.L.',       articulo: 'BA478',  provincia: 'Santa Fe', ventaActual: 8.5,  varDinero: -0.6,  unidadesActual: 715,  varUnidades: -50 },
    { cliente: 'Casa Hidráulica S.R.L.',       articulo: 'BA442',  provincia: 'Santa Fe', ventaActual: 7.3,  varDinero: -0.5,  unidadesActual: 770,  varUnidades: -40 },
    { cliente: 'Autorepuestos Andina S.A.',    articulo: 'BA1473', provincia: 'Mendoza',  ventaActual: 7.8,  varDinero: 2.5,   unidadesActual: 760,  varUnidades: 240 },
    { cliente: 'Autorepuestos Andina S.A.',    articulo: 'BA691',  provincia: 'Mendoza',  ventaActual: 6.2,  varDinero: 2.1,   unidadesActual: 700,  varUnidades: 230 },
  ],
};
